### ISSUE TITLE
压缩包无法解压

### ISSUE THREAD

**Issue by laohua2023** [deepin-community/deepin-rootfs#10]
v1.2.0
deepin-rootfs-arm64.tar.gz

压缩包的后缀不对。
下载下来的文件， 发现实际是个tar包，并没有压缩过

**Comment by laohua2023** [comment]
这个仓库，是官方吗？

**Comment by chenchongbiao** [comment]
> 这个仓库，是官方吗？

是的。

**Comment by chenchongbiao** [comment]
> v1.2.0 deepin-rootfs-arm64.tar.gz
> 
> 压缩包的后缀不对。 下载下来的文件， 发现实际是个tar包，并没有压缩过

嗷，打包脚本用的 tar -cf ,少写了z参数，要解压这个的话，用 tar -xf

**Comment by chenchongbiao** [comment]
- [x] [修复tar 命令缺少 -z 参数](https://github.com/deepin-community/deepin-rootfs/commit/f1bd5eb2addafb72adbd7032d54eedeff158ad8d)
