### ISSUE TITLE
有个wget的文案错误

### ISSUE THREAD

**Issue by Re-s** [deepin-community/deepin-rootfs#4]
这里有个文案错误，wget写成了dget。
![image](https://github.com/deepin-community/deepin-rootfs/assets/21084897/0be9beb7-d80d-482c-a7b4-07a02e61d4ca)

**Comment by chenchongbiao** [comment]
这是由devscripts提供的dget命令，用来下载源代码的，源代码不止dsc文件，但是用dget命令可以只通过dsc文件的url把源代码相关的文件都下载下来。
