### ISSUE TITLE
按照教程。直接wsl service报错了

### ISSUE THREAD

**Issue by springeye** [deepin-community/deepin-rootfs#5]
![image](https://github.com/deepin-community/deepin-rootfs/assets/1314740/1d91389b-1460-4605-bcbf-ca8951c1d657)

**Comment by chenchongbiao** [comment]
感谢你的反馈。
你用的操作系统是不是 Windows 11，或者看下 WSL 版本低于 0.67.6。目前，微软官方支持的 systemd 特性只适用于 Windows 11 和 WSL 0.67.6 或更高版本。
你可以通过 wsl --version 命令查看你的 WSL 版本，如果低于 0.67.6，你可以通过微软应用商店或 GitHub 下载最新的 WSL 预览版。
不然这个systemd服务你可以考虑不开启，不过就是有些守护进程无法启动。

**Comment by springeye** [comment]
都是最新版，systemed是支持的。wsl里的ubuntu都开启了的。
![image](https://github.com/deepin-community/deepin-rootfs/assets/1314740/41e88300-8191-4b02-91a1-3d92c9fcaf71)

![image](https://github.com/deepin-community/deepin-rootfs/assets/1314740/ad4e406c-43d5-4a65-93f1-355e5418c523)

**Comment by chenchongbiao** [comment]
因为我在win11测的时候大部分没有问题，不确定这是不是偶发现象，你可以尝试`wsl --unregister deepin` 来删除deepin wsl,再重新尝试一次。
或者你尝试了手动打开那个/etc/wsl.conf文件，来编辑那个开启systemd的配置。
```bash
[boot]
systemd=true
```

**Comment by springeye** [comment]
我测试了，只要启用了systemd 就不信。手动编译wsl.conf也不行。

**Comment by chenchongbiao** [comment]
你用一下`wsl -l -v` 我看一下

**Comment by springeye** [comment]
> 你用一下`wsl -l -v` 我看一下

<img width="621" alt="image" src="https://github.com/deepin-community/deepin-rootfs/assets/1314740/68dba8ce-6654-4321-9f51-6f486f829a14">

**Comment by CrescentSine** [comment]
我试了今天最新版本的包，也是同样的问题，一打开systemd就不行

**Comment by LiangQinghai** [comment]
今天尝试了最新包也是同样的问题
![image](https://github.com/deepin-community/deepin-rootfs/assets/26506161/729743f6-d2e4-43a7-bddf-93de78b1b9bf)

**Comment by chenchongbiao** [comment]
> 今天尝试了最新包也是同样的问题 ![image](https://user-images.githubusercontent.com/26506161/261339426-729743f6-d2e4-43a7-bddf-93de78b1b9bf.png)

好的，我注意到你们都是win10 系统，我会去尝试下在win10配置一下。

**Comment by LiangQinghai** [comment]
> > 今天尝试了最新包也是同样的问题 ![image](https://user-images.githubusercontent.com/26506161/261339426-729743f6-d2e4-43a7-bddf-93de78b1b9bf.png)
> 
> 好的，我注意到你们都是win10 系统，我会去尝试下在win10配置一下。

![image](https://github.com/deepin-community/deepin-rootfs/assets/26506161/44f6357f-7922-4fa5-81a7-7f7ac793bd18)

应该都是win11，wsl --version展示的微软的内部版本号，这个链接：[windows版本](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8)。

另外，我重新删掉结合着这个[教程](https://github.com/chenchongbiao/os-study/tree/master/dev-env/wsl)成功了.

![image](https://github.com/deepin-community/deepin-rootfs/assets/26506161/9a14579a-723a-4e31-9ceb-d88ca938b7ee)

**Comment by chenchongbiao** [comment]
ok 我去修改下教程

**Comment by chenchongbiao** [comment]
重新发了一份，https://github.com/deepin-community/deepin-rootfs/releases/tag/v1.1.0-x64，可以下载 cer 证书需要安装，参考 https://blog.csdn.net/egostudio/article/details/77408126，另外的 deepinWSL-Appx_1.1.0_x64.appxbundle 是使用微软提供的分发工具重新制作的。双击运行后，直接提示创建密码，不用像教程那样手动添加一个用户了。
